### PR TITLE
fix: default boolean properties to false

### LINKED ISSUE #27: auro-icon: boolean properties need default values
## Describe the bug
The following properties do not have a default value:

- primary
- label
- emphasis
- accent
- disabled
- error
- success
- advisory
- warning
- customColor

This prevents Svelte apps from using the boolean attribute shorthand, e.g. `<auro-icon primary>`.

## Expected behavior
The above properties have a default value.

### PR DESCRIPTION
**Pull request by geoffrich**
# Alaska Airlines Pull Request

Fixes #27

## Summary:

Defaults boolean properties to false.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by jason-capsule42 — APPROVED** [review]

**Comment by blackfalcon** [comment]
Please add the number of the issue to the commit message so that we have a quick reference to the issue in the log.

**Comment by geoffrich** [comment]
@blackfalcon sorry, I think it's too late to do that for this PR. I will update the commits on the PRs that are still open.

**Comment by blackfalcon** [comment]
Opps, I meant... "Please [remember]..." 

Thanks!

**Pull request merged**
